#!/usr/bin/env bash

set -uo pipefail

AUTHFILE_TARGET="$HOME/.s3ql/authinfo2"

function help() {
  echo ""
  echo "Usage:"
  echo "  s3qlw_import_authfile [source]"
  echo ""
}

SOURCE_FILE=${1:-}
if [ -z "$SOURCE_FILE" ]; then
  echo "Error: Source file is not set!"
  help
  exit 1
fi

if ! [ -f "$SOURCE_FILE" ]; then
  echo "Error: Source file [$SOURCE_FILE] not found!"
  exit 1
fi
echo "Using source file: [$SOURCE_FILE]"

set -x
install \
  -v \
  -D \
  -m 0600 \
  "$SOURCE_FILE" \
  "$AUTHFILE_TARGET"
