#!/usr/bin/env bash

set -uo pipefail

function help() {
  echo ""
  echo "Usage:"
  echo "  s3qlw_mount [storage-url] [mountpoint]"
  echo ""
}

STORAGE_URL=${1:-}
if [ -z "$STORAGE_URL" ]; then
  echo "Error: Storage url not defined!"
  help
  exit 1
fi
echo "Using storage url: [$STORAGE_URL]"

MOUNTPOINT=${2:-}
if [ -z "$MOUNTPOINT" ]; then
  echo "Error: Mountpoint not defined!"
  help
  exit 1
fi
echo "Using mountpoint: [$MOUNTPOINT]"

set -x
mount.s3ql --allow-other "$STORAGE_URL" "$MOUNTPOINT"
