#!/usr/bin/env bash

set -uo pipefail

function help() {
  echo ""
  echo "Usage:"
  echo "  s3qlw_unmount [mountpoint]"
  echo ""
}

MOUNTPOINT=${1:-}
if [ -z "$MOUNTPOINT" ]; then
  echo "Error: Mountpoint not defined!"
  help
  exit 1
fi
echo "Will unmount: [$MOUNTPOINT]"

set -x
umount.s3ql "$MOUNTPOINT"
